# Generated by Django 4.2.6 on 2023-10-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Username Example : @vop_org'),
        ),
    ]
