# Generated by Django 4.2.6 on 2023-10-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expire_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
