# Generated by Django 4.2.6 on 2023-10-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0003_alter_subscription_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='limit_user',
            field=models.IntegerField(default=1),
        ),
    ]
