# Generated by Django 4.2.6 on 2023-10-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0006_delete_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='limit_user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='period_of_time',
            field=models.IntegerField(default=1, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expire_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
