# Generated by Django 4.2.6 on 2023-10-11 12:39

import app_subscription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0007_remove_subscription_limit_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='code',
            field=models.CharField(default=app_subscription.models.generate_unique_code, max_length=255, unique=True),
        ),
    ]
