# Generated by Django 4.2.6 on 2023-12-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servers', '0002_alter_servers_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='config',
            field=models.TextField(),
        ),
    ]
